### ISSUE TITLE
Input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by kerloom** [CarlSouthall/ADTLib#1]
Thanks for releasing this library!

I was trying it out first with some wave files I had, which gave me no problems. I later tried to convert an mp3 to wav using ffmpeg (mono, 44.1KHz):
`ffmpeg -i in.mp3 -acodec pcm_s16le -ac 1 -ar 44100 out.wav`

When using default settings I get the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-50059aaecf0f> in <module>()
----> 1 out=ADTBDRNN(['/home/cuaras/out.wav'])

/home/cuaras/Documents/workspace/drum/venv/lib/python2.7/site-packages/ADTLib/models/__init__.pyc in ADTBDRNN(TrackNames, out_sort, ret, out_text, savedir, close_error, lambd)
     83             P[j][i]=peak
     84 
---> 85     P=arrange_output(P,output_sort=out_sort)
     86 
     87     if out_text == 'yes':

/home/cuaras/Documents/workspace/drum/venv/lib/python2.7/site-packages/ADTLib/utils/__init__.pyc in arrange_output(Inputs, output_sort)
     44                 Out[i][j][k][1]=Names[j]
     45 
---> 46         Out[i]=np.concatenate([Out[i][0],Out[i][1],Out[i][2]],axis=0)
     47 
     48         if output_sort=='time':

ValueError: all the input arrays must have same number of dimensions
```

Maybe it's some configuration error on my part. Here is the link to the file:
https://dl.dropboxusercontent.com/u/12497232/out.wav

**Comment by CarlSouthall** [comment]
Hi Jorge,

Sorry for the late reply I have been on vacation for the past week.

Thank you for bringing this to my attention, I have made corrections so it should now work if you reinstall / update the ADTLib package.

Unfortunately the library is not really trained on metal / clicky kick drums at the moment and so struggles to identify the kick drum onsets in that track.

Thanks
Carl

**Comment by kerloom** [comment]
Thank you, it works now! I was just beginning trying it out.
