### ISSUE TITLE
Only half of the song is processed?

### ISSUE THREAD

**Issue by cicaglisa80** [CarlSouthall/ADTLib#6]
Hi Carl,
I was trying to run your algo on couple of songs but I've noticed whatever I pass as input I will always get only half of the song processed. For instance if I pass 20 seconds in input I can see only BD, SD and HH up to 10 seconds same if I double those values. Any idea of why this might be happening?

**Comment by CarlSouthall** [comment]
Hi,

this should now be fixed in the latest update, thanks.
